## Begin helm/k8s constraints
### To build out the list of overrides, see kubernetes/kubernetes/Godeps/Godeps.json

required = [
    "github.com/go-openapi/spec",
    "github.com/emicklei/go-restful"
]

ignored = [
    "k8s.io/client-go/pkg/*"
]

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.9.2"

[[override]]
  name = "github.com/russross/blackfriday"
  version ="~v1.4"

[[constraint]]
  name = "k8s.io/helm"
  version = "~v2.8.0"

[[override]]
  name = "github.com/docker/distribution"
  revision = "b38e5838b7b2f2ad48e06ec4b500011976080621"

[[override]]
  name = "github.com/emicklei/go-restful"
  version = "~v2.2"

## End helm/k8s constraints

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~v0.8.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "~v1.3.0"

[[constraint]]
  name = "code.cloudfoundry.org/lager"
  version = "~v1.0.0"

[[constraint]]
  name = "github.com/pivotal-cf/brokerapi"
  branch = "master"

[[constraint]]
  name = "github.com/gosuri/uitable"
  revision = "36ee7e946282a3fb1cfecd476ddc9b35d8847e42"
