### Begin helm/k8s constraints

required = [
    "github.com/go-openapi/spec"
]

ignored = [
    "k8s.io/client-go/pkg/*"
]

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.8.7"

[[constraint]]
  name = "k8s.io/helm"
  version = "~v2.7.0"

# figured out this override using Draft
[[override]]
  name = "github.com/docker/distribution"
  revision = "b38e5838b7b2f2ad48e06ec4b500011976080621"

### End helm/k8s constraints

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~v0.8.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "~v1.3.0"

[[constraint]]
  name = "code.cloudfoundry.org/lager"
  branch = "master"

[[constraint]]
  name = "github.com/pivotal-cf/brokerapi"
  branch = "master"
